"""add medical record transfer table

Revision ID: add_medical_record_transfer
Revises: add_organization_modules
Create Date: 2026-02-22 11:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_medical_record_transfer'
down_revision = 'add_organization_modules'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_record_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('medical_record_id', sa.Integer(), nullable=False),
    sa.Column('sent_by_doctor_id', sa.Integer(), nullable=False),
    sa.Column('recipient_name', sa.String(length=255), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('recipient_facility', sa.String(length=255), nullable=True),
    sa.Column('recipient_specialty', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('patient_consent', sa.Boolean(), nullable=False, server_default='1'),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', name='transfer_status'), nullable=False, server_default='pending'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['medical_record_id'], ['medical_records.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['sent_by_doctor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medical_record_transfers', schema=None) as batch_op:
        batch_op.create_index('idx_transfer_org_patient', ['organization_id', 'patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_record_transfers_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_record_transfers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_record_transfers_organization_id'))
        batch_op.drop_index('idx_transfer_org_patient')

    op.drop_table('medical_record_transfers')
    # ### end Alembic commands ###
