"""add organization modules

Revision ID: add_organization_modules
Revises: ff333cdccc7c
Create Date: 2026-02-22 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_organization_modules'
down_revision = 'ff333cdccc7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('module_doctor', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('module_receptionist', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('module_lab_technician', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('module_pharmacist', sa.Boolean(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('module_pharmacist')
        batch_op.drop_column('module_lab_technician')
        batch_op.drop_column('module_receptionist')
        batch_op.drop_column('module_doctor')
    # ### end Alembic commands ###
