"""Add prescription and pharmacy inventory models

Revision ID: bc4eecff8a4c
Revises: 
Create Date: 2026-02-05 16:45:35.927920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc4eecff8a4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pharmacy_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('medication_name', sa.String(length=200), nullable=False),
    sa.Column('generic_name', sa.String(length=200), nullable=True),
    sa.Column('brand_name', sa.String(length=200), nullable=True),
    sa.Column('dosage_form', sa.String(length=100), nullable=True),
    sa.Column('strength', sa.String(length=100), nullable=True),
    sa.Column('quantity_in_stock', sa.Integer(), nullable=False),
    sa.Column('minimum_stock_level', sa.Integer(), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('storage_location', sa.String(length=100), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('supplier', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_restocked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'medication_name', 'strength', 'batch_number', name='_org_medication_batch_uc')
    )
    with op.batch_alter_table('pharmacy_inventory', schema=None) as batch_op:
        batch_op.create_index('idx_inventory_org_med', ['organization_id', 'medication_name'], unique=False)
        batch_op.create_index('idx_inventory_org_stock', ['organization_id', 'quantity_in_stock'], unique=False)
        batch_op.create_index(batch_op.f('ix_pharmacy_inventory_organization_id'), ['organization_id'], unique=False)

    op.create_table('prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('medical_record_id', sa.Integer(), nullable=True),
    sa.Column('medication_name', sa.String(length=200), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'dispensed', 'partially_dispensed', 'cancelled', 'referred', name='prescription_status'), nullable=False),
    sa.Column('dispensed_quantity', sa.Integer(), nullable=True),
    sa.Column('dispensed_by_id', sa.Integer(), nullable=True),
    sa.Column('dispensed_at', sa.DateTime(), nullable=True),
    sa.Column('referral_notes', sa.Text(), nullable=True),
    sa.Column('referred_by_id', sa.Integer(), nullable=True),
    sa.Column('referred_at', sa.DateTime(), nullable=True),
    sa.Column('prescribed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dispensed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['medical_record_id'], ['medical_records.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['referred_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.create_index('idx_prescription_org_date', ['organization_id', 'prescribed_at'], unique=False)
        batch_op.create_index('idx_prescription_org_patient', ['organization_id', 'patient_id'], unique=False)
        batch_op.create_index('idx_prescription_org_status', ['organization_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescriptions_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescriptions_organization_id'))
        batch_op.drop_index('idx_prescription_org_status')
        batch_op.drop_index('idx_prescription_org_patient')
        batch_op.drop_index('idx_prescription_org_date')

    op.drop_table('prescriptions')
    with op.batch_alter_table('pharmacy_inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pharmacy_inventory_organization_id'))
        batch_op.drop_index('idx_inventory_org_stock')
        batch_op.drop_index('idx_inventory_org_med')

    op.drop_table('pharmacy_inventory')
    # ### end Alembic commands ###
