"""add_billing_tables

Revision ID: e4a5b5f8ccdb
Revises: add_prescription_notif
Create Date: 2026-02-19 21:21:22.390644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4a5b5f8ccdb'
down_revision = 'add_prescription_notif'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('bill_number', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('open', 'pending_payment', 'partially_paid', 'paid', 'cancelled', name='bill_status'), nullable=False),
    sa.Column('payment_method', sa.Enum('cash', 'card', 'insurance', 'mobile_money', 'bank_transfer', 'other', name='payment_methods'), nullable=True),
    sa.Column('payment_reference', sa.String(length=200), nullable=True),
    sa.Column('payment_notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('paid_to_id', sa.Integer(), nullable=True),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['paid_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'bill_number', name='_org_bill_number_uc')
    )
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.create_index('idx_bill_org_date', ['organization_id', 'visit_date'], unique=False)
        batch_op.create_index('idx_bill_org_patient', ['organization_id', 'patient_id'], unique=False)
        batch_op.create_index('idx_bill_org_status', ['organization_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bills_organization_id'), ['organization_id'], unique=False)

    op.create_table('bill_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Enum('consultation', 'lab_test', 'medication', 'procedure', 'other', name='bill_item_types'), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('lab_test_id', sa.Integer(), nullable=True),
    sa.Column('prescription_id', sa.Integer(), nullable=True),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('medical_record_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['lab_test_id'], ['lab_tests.id'], ),
    sa.ForeignKeyConstraint(['medical_record_id'], ['medical_records.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bill_items', schema=None) as batch_op:
        batch_op.create_index('idx_bill_item_bill', ['bill_id'], unique=False)
        batch_op.create_index('idx_bill_item_type', ['organization_id', 'item_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_bill_items_bill_id'), ['bill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bill_items_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('notification_type',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('lab_result', 'appointment', 'referral', 'system', 'urgent', 'prescription', name='notification_types'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('notification_type',
               existing_type=sa.Enum('lab_result', 'appointment', 'referral', 'system', 'urgent', 'prescription', name='notification_types'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)

    with op.batch_alter_table('bill_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bill_items_organization_id'))
        batch_op.drop_index(batch_op.f('ix_bill_items_bill_id'))
        batch_op.drop_index('idx_bill_item_type')
        batch_op.drop_index('idx_bill_item_bill')

    op.drop_table('bill_items')
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bills_organization_id'))
        batch_op.drop_index('idx_bill_org_status')
        batch_op.drop_index('idx_bill_org_patient')
        batch_op.drop_index('idx_bill_org_date')

    op.drop_table('bills')
    # ### end Alembic commands ###
