"""add facility registration requests table

Revision ID: f3d3ce085f18
Revises: bc4eecff8a4c
Create Date: 2026-02-17 21:47:13.942282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3d3ce085f18'
down_revision = 'bc4eecff8a4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facility_registration_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_name', sa.String(length=255), nullable=False),
    sa.Column('facility_type', sa.Enum('hospital', 'clinic', 'pharmacy', 'laboratory', 'other', name='facility_types'), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('contact_person_name', sa.String(length=255), nullable=False),
    sa.Column('contact_person_email', sa.String(length=120), nullable=False),
    sa.Column('contact_person_phone', sa.String(length=20), nullable=False),
    sa.Column('contact_person_position', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('number_of_staff', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='request_status'), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)

    op.drop_table('facility_registration_requests')
    # ### end Alembic commands ###
