"""add_prescription_pickup_status

Revision ID: ff333cdccc7c
Revises: e4a5b5f8ccdb
Create Date: 2026-02-19 22:14:02.818873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff333cdccc7c'
down_revision = 'e4a5b5f8ccdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picked_up_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('picked_up_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_prescriptions_picked_up_by_id', 'users', ['picked_up_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_prescriptions_picked_up_by_id', type_='foreignkey')
        batch_op.drop_column('picked_up_by_id')
        batch_op.drop_column('picked_up_at')

    # ### end Alembic commands ###
